@startuml

title Go-Tamboon

participant "Client(Telenor)" as Client 
participant DCBBackend
participant DCBDatabaseTable
participant DCBDatabaseStoreProcedure
participant AmazonWebServiceSQS
participant "DCB API-Gateway" as APIGateway